repos:
- repo: https://github.com/psf/black
  rev: '23.1.0'
  hooks:
    - id: black
      language_version: python3.9
      name: formatter (python)
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: fix imports (python)
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.257'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      name: linter (python)