[tool.ruff]
line-length = 120
target-version = "py39"

[tool.ruff.flake8-quotes]
docstring-quotes = "single"

[tool.black]
line-length = 120
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
py_version = 39
line_length = 120
profile = "black"
lines_after_imports = 2
force_single_line = true
src_paths = ["src", "test"]
remove_redundant_aliases = true
skip = [".gitignore", ".dockerignore"]
force_alphabetical_sort_within_sections = true
known_first_party = ["tests",]

[tool.pytest.ini_options]
asyncio_mode = 'auto'
testpaths = [
    "tests",
]
